# Generated by Django 2.2.1 on 2019-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='repo',
            field=models.CharField(max_length=100),
        ),
    ]
