---
- hosts: all
  remote_user: student
  become: yes
  tasks:
  - name: Installing git
    become_user: root
    become_method: su
    yum:
       name: git
       state: latest
  - name: Clone app from repo
    git:
       repo: 'https://github.com/anbogdan/webapp.git'
       dest: /home/student
       version: master
