---
- hosts: all
  remote_user: student
  tasks:
  - name: Installing git
    yum:
       name: git
       state: latest
    become: yes
    become_user: root
  - name: Clone app from repo
    git:
       repo: 'https://github.com/anbogdan/dummy.git'
       dest: /home/student/app
