- hosts: all
  remote_user: student
  tasks:
  - name: Clone app from repo
    git:
       repo: 'https://github.com/anbogdan/webapp.git'
       dest: /var/www
  - name: Install python3
    yum:
      name: python3
      state: latest
    become: yes
    become_user: root
  - name: Install requirements
    pip:
      requirements: /var/www/webapp/requirements.txt
  - name: Run server
    shell: python /var/www/webapp/mysite/manage.py runserver </dev/null >/dev/null 2>&1 &
