- hosts: all
  remote_user: student
  tasks:
  - name: Clone app from repo
    git:
       repo: 'https://github.com/anbogdan/webapp.git'
       dest: /var/www
    become: yes
    become_user: root
  - name: Update yum
    yum:
      name: https://centos7.iuscommunity.org/ius-release.rpm
      state: latest
    become: yes
    become_user: root
  - name: Install python36
    yum:
      name: python36
      state: latest
    become: yes
    become_user: root
  - name: Install pip3
    yum:
      name: python36-pip
      state: latest
    become: yes
    become_user: root
  - name: Install requirements
    pip3:
      requirements: /var/www/webapp/requirements.txt
  - name: Run server
    shell: python /var/www/webapp/mysite/manage.py runserver </dev/null >/dev/null 2>&1 &
