# Generated by Django 2.2.1 on 2019-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flv_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=20)),
                ('ram', models.FloatField()),
                ('vcpu', models.IntegerField()),
                ('disk', models.IntegerField()),
            ],
        ),
    ]
