# Generated by Django 2.2.1 on 2019-06-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flavors',
            new_name='Flavor',
        ),
    ]
