# Generated by Django 2.2.1 on 2019-06-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_apis', '0003_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
